Portfolio project pull request
sibomana123/Microverse-protofolio pull request #1
Opened 2023-04-28 09:48 UTC by sibomana123

this branch contain index html css and all page , is what i prepare tomake pull request

2023-04-28 11:18 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @sibomana123   👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)
## Highlight 
✔ Used the correct Git Flow 👍 
✔ No Linter Errors👍 
✔ Responsive web design👍 
## Required Changes ♻️

- [ ]  Check the comments below 

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 11:18 UTC, TuyishimireEric commented on index.html
> +          <li><img  class="icon_image"src="images/medium.svg" alt=""></li>
- [ ] **Good job on using `ul` tag to group, and `li` for the icons 👏 👏** However it would be better for each icon to add **a link (`a` tag)**.
    
    Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using `href`. 😎😎

- [ ] It would be better also to replicate the Figma styling on these icons for the best user interface 👍 👍 

**Your design** | **Figma design**
| --- | --- |
![image](https://user-images.githubusercontent.com/102757126/235131886-b6173e0c-3a86-47a6-8a3a-4dad17770ef6.png) | ![image](https://user-images.githubusercontent.com/102757126/235131950-78aba99a-379c-47f9-9cab-e479619a2d61.png)

2023-04-28 11:18 UTC, TuyishimireEric commented on style.css
> +}
## Styling ✨✨
- [ ] **Kudos on making your web page responsive``` 👏 👏** However, it would be better to replicate the [Figma design ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39-122&t=wMKvp4oyMqZ6YudA-0) as much as possible by using the same background size and position 🙏 
- [ ] It would be better also to make some adjustments to the typography ```(font-size, font-weight, spacing)``` to replicate the chosen Figma design 😎😎 
   
  **_You may kindly try to match the following 👇_**
    
   ![image](https://user-images.githubusercontent.com/102757126/235133828-735fe593-1dd9-4179-9086-1215ea109dcf.png)

2023-04-28 18:31 UTC, Owusu-Desmond requested changes
Hi @sibomana123  :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 18:31 UTC, Owusu-Desmond commented on index.html
> +      <ul class="nav__links">
- [ ] While working on the changes the previous code reviewer suggested your logo is not aligned at the left as it is in the Figma design.
  
  ![image](https://user-images.githubusercontent.com/92303891/235224065-0f4c0363-0b9b-4265-a955-3f24acda41af.png)

2023-04-28 18:31 UTC, Owusu-Desmond commented on style.css
> +}
- [ ] As requested before It would be better also to make some adjustments to the typography (`font-size, font-weight, line-spacing and font-family`) to match the chosen Figma design 
  
  ### Your design
    ![image](https://user-images.githubusercontent.com/92303891/235224357-a659a424-2f03-4710-bc55-b72d1781312c.png)
   
  ### Figma design
  ![image](https://user-images.githubusercontent.com/92303891/235225854-53c3430c-22ea-4571-b27a-ee533281520b.png)

2023-05-01 09:12 UTC, LionRouge1 reviewed
Hi @sibomana123, 

![done](https://media.giphy.com/media/gnE4FFhtFoLKM/giphy.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't follow GitHub flow (Your branch name should have a feature or action name (e.g. "setup_mobile_first" or "mobile_first"). Kindly create a new branch with a semantic name representing what is in the branch and refer to this PR in the new PR that you will create.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-01 09:18 UTC, closed without merging