Mobile first pull requset
sibomana123/Microverse-protofolio pull request #2
Opened 2023-05-01 09:32 UTC by sibomana123

pull request of html css and image of portfolio project

2023-05-01 09:44 UTC, stanleySimeon requested changes
Hi @sibomana123 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# ⚠️ Invalid Code Review Request ⚠️ 

You have submitted a project, that does not have a descriptive Pull Request (PR). The PR descriptions should contain a summary of the changes you have in the project/PR. This gives the reviewer an idea of the changes that took place in this particular PR. Kindly fix this before requesting another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @stanleySimeon in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-01 10:46 UTC, Abenezer-Tilahun requested changes
Hi @sibomana123     , 

Great job for implemented  the some of the Project Requirement , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No linters error
✔️ You used correct Git Hub-Flow.
✔️ Good README 
✔️ Good Commit Messages 


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [ ] Kindly I recommend you to update your READEME file to include the **"Feature section "**  including 1-3 potential features to be added and please before push the READEME file to main branch kindly make sure that you update in your feature branch(here).

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 10:46 UTC, Abenezer-Tilahun commented on index.html
> +    <div><a  class="logo"   href="#Home">My Logo</a></div>
- [ ] Kindly I recommend you to make the "My Logo" outside the `nav` tag for his is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info Just Like this : 
```
<header class="header__nav">
 <div><a  class="logo"   href="#Home">My Logo</a></div>
    <nav class="navbar">
 <ul class="nav__links">
        <li><a href="#portfolio">Portfolio</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><img src="images/Union.png" alt=""></li>
      </ul>
      <img class="menu" src="images/menu.svg" alt="">
    </nav>

  </header>
```

2023-05-01 10:46 UTC, Abenezer-Tilahun commented on index.html
> +          <h6>I’m a Software Developer</h6>
- [ ] Kindly i recommend you to use` h1` tag fro the main title("Hey There. I’m Alex.") and` hx(h2)` tag for the subtitle("I’m a Software Developer") instead of `h6` tag . This way will be semantically correct and the screen readers and other technologies will thank you.

2023-05-01 10:46 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ ] Kindly make sure that Your website should look exactly like the design (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Kindly adjust the responsive, just the project requirement by using the breakpoints **Minimum mobile screen size should be 375px** instead of max-width=375px,Kindlu Fix it.
- Your Website Toolbar at 375px 
![Capture](https://user-images.githubusercontent.com/93598189/235441701-b6d50de1-9912-4c63-a7b9-19b67faa93d5.PNG)

- The Figma Design Toolbar Look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/235441794-7651aa51-72e8-409a-abe2-6fae3b0abe80.PNG)

- Your Website Headline section Look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/235441951-865deb1e-7985-4004-ad3e-0065c7555fcf.PNG)

- The Figma Headline section Look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/235442094-4a83cc62-2879-4456-a6cc-3153e3c21667.PNG)

2023-05-01 14:57 UTC, wickathou commented
Hi @sibomana123 , 

Unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request :heavy_multiplication_x:

## You have submitted a project, with the following issues:

### Your project's linters are not working
> It is a requirement for every project you work on, that your linters work appropriately
> https://github.com/microverseinc/linters-config/tree/master/html-css
> I suggest you go through the setup documentation in detail to make them work on your repo

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-01 15:26 UTC, GedeonTS requested changes
# INVALID REVIEW REQUEST

Hi @sibomana123 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

You have submitted a project, that is not well documented. Kindly make sure to add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-01 17:03 UTC, stanleySimeon requested changes
# Hi @sibomana123 
 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media2.giphy.com/media/vQGBDTkhtIunaJYmRF/giphy-downsized.gif?cid=29caca75sf3uq9y4qgulk5ybbojwg94b4zo6temfzeel417x&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g
)

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Meaningful commit messages ✔️

# Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @stanleySimeon in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 17:03 UTC, stanleySimeon commented on index.html
> +  </section>
As mentioned by the previous reviewer, kindly make sure that Your website should look exactly like the design (e.g. font, colors, images, text, margins) using [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) template.

>### The Figma design
>
><img width="291" alt="Screenshot 2023-05-01 at 13 01 42" src="https://user-images.githubusercontent.com/91237525/235493059-a0020982-64d7-4fbd-bab5-a40dfc413e52.png">
>
>### Your Design
>
><img width="358" alt="Screenshot 2023-05-01 at 13 02 16" src="https://user-images.githubusercontent.com/91237525/235493136-f4b4ae3a-87de-44a5-9b6b-6245854c3c49.png">

2023-05-02 10:31 UTC, AlphaNtihinduka requested changes
## Hi @sibomana123 🙋‍♂️
Good job working on implementing the changes required by the previous reviewers. You have done the design to do the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is not yet professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- [ ] I have noticed that you applied the required changes in the new checked out `feature` branch :+1: :clap: . This is a great mile stone achievement. 
### To ensure that your project meets the standard requirements: 
Kindly submit the this [pull request link](https://github.com/Koshao-sys/Hello-world/pull/2) where you applied the required changes :recycle: . Then in the description, mention the old [PR](

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-05-02 10:31 UTC, AlphaNtihinduka commented on index.html
> +      />
- [ ] I have noticed that the `illustration.svg` was edited to `illust.svg`, therefore the background image can not be displayed. Kindly add the image so that the portifolio matches the Figma template design ☺️.
- [ ] [OPTIONAL] In addition, since this is an image used to style the headline, you should consider adding it as a background image using CSS instead of adding it as an image tag 👍.

Your previous design 😎 
![image](https://user-images.githubusercontent.com/99394374/235641275-ace7d9c9-836e-4843-bfe6-b580f0489941.png)

Your current design 😎 
![image](https://user-images.githubusercontent.com/99394374/235643389-eece4a7a-a2ca-42bb-b6e4-637c5f2ff4e7.png)

2023-05-02 10:58 UTC, Strangeal approved these changes
Hi @sibomana123, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 11:27 UTC, merged